---
- hosts: all
  become: yes
  tasks:
    - name: install tcpdump
      package: name=tcpdump state=present
    - name: install traceroute
      package: name=traceroute state=present
    - name: install nmap
      package: name=nmap state=present

- hosts: router
  become: yes
  tasks:
    - name: allow ipv4 traffic forwarding
      sysctl: name=net.ipv4.ip_forward value=1 state=present
    - name: forward 10.0.0.0/24 traffic to 172.16.0.0/24
      iptables:
        chain: FORWARD
        in_interface: enp0s9
        out_interface: enp0s8
        source: '172.16.0.0/24'
        destination: '10.0.0.0/24'
        jump: ACCEPT
    - name: forward 172.16.0.0/24 traffic to 10.0.0.0/24
      iptables:
        chain: FORWARD
        in_interface: enp0s8
        out_interface: enp0s9
        source: '10.0.0.0/24'
        destination: '172.16.0.0/24'
        jump: ACCEPT

- hosts: host01
  become: yes
  tasks:
    - name: add route to 172.16.0.0/24
      command: ip route add 172.16.0.0/24 via 10.0.0.1 dev enp0s8

- hosts: host02
  become: yes
  tasks:
    - name: add route to 10.0.0.0/24
      command: ip route add 10.0.0.0/24 via 172.16.0.1 dev enp0s8
